import type { Icons as IconsType } from '@/types';

export const Icons: typeof IconsType = [
    'bell-mute',
    'bell',
    'brush',
    'camera',
    'checkmark',
    'clock',
    'download',
    'gear',
    'globe',
    'house',
    'info',
    'link',
    'lock',
    'pin',
    'plus',
    'redirect',
    'redo',
    'shield',
    'sun',
    'trash',
    'undo',
    'unlock',
    'upload',
    'wand',
    'warning',
];
