export declare const color: ((color?: import("../base/color").Color | undefined, fallback?: import("../base/color").Color | undefined) => string) & {
    green: `#${string}`;
    yellow: `#${string}`;
    orange: `#${string}`;
    red: `#${string}`;
    teal: `#${string}`;
    blue: `#${string}`;
    indigo: `#${string}`;
    purple: `#${string}`;
    pink: `#${string}`;
    gray10: `#${string}`;
    gray9: `#${string}`;
    gray8: `#${string}`;
    gray7: `#${string}`;
    gray6: `#${string}`;
    gray5: `#${string}`;
    gray4: `#${string}`;
    gray3: `#${string}`;
    gray2: `#${string}`;
    gray1: `#${string}`;
} & {
    colors: {
        green: `#${string}`;
        yellow: `#${string}`;
        orange: `#${string}`;
        red: `#${string}`;
        teal: `#${string}`;
        blue: `#${string}`;
        indigo: `#${string}`;
        purple: `#${string}`;
        pink: `#${string}`;
        gray10: `#${string}`;
        gray9: `#${string}`;
        gray8: `#${string}`;
        gray7: `#${string}`;
        gray6: `#${string}`;
        gray5: `#${string}`;
        gray4: `#${string}`;
        gray3: `#${string}`;
        gray2: `#${string}`;
        gray1: `#${string}`;
    };
};
