"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppStyles = void 0;
var styled_components_1 = require("styled-components");
var fonts_1 = require("./fonts");
// NOTE: background-color transition for theme switch
exports.AppStyles = (0, styled_components_1.createGlobalStyle)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    ", "\n\n    #dev-toolkit {\n        font-family: ", ";\n        line-height: 1.3;\n        letter-spacing: .02em;\n        ", "\n    }\n\n    #dev-toolkit pre, kbd, code, samp {\n        font-family: ", ";\n    }\n\n    #dev-toolkit *::placeholder {\n        font-weight: 400;\n        color: ", " !important;\n    }\n\n    #dev-toolkit input[type=\"password\"]::placeholder {\n        font-weight: 700;\n        letter-spacing: .4em;\n    }\n"], ["\n    ", "\n\n    #dev-toolkit {\n        font-family: ", ";\n        line-height: 1.3;\n        letter-spacing: .02em;\n        ", "\n    }\n\n    #dev-toolkit pre, kbd, code, samp {\n        font-family: ", ";\n    }\n\n    #dev-toolkit *::placeholder {\n        font-weight: 400;\n        color: ", " !important;\n    }\n\n    #dev-toolkit input[type=\"password\"]::placeholder {\n        font-weight: 700;\n        letter-spacing: .4em;\n    }\n"])), fonts_1.SourceCodePro, function (p) { return p.theme.text.System.family; }, function (p) { return p.$animations ? '' : (0, styled_components_1.css)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n            animation-delay: 0s !important;\n            animation-duration: 0s !important;\n            transition-delay: 0s !important;\n            transition-duration: 0s !important;\n\n            ::after,\n            ::before {\n                animation-delay: 0s !important;\n                animation-duration: 0s !important;\n                transition-delay: 0s !important;\n                transition-duration: 0s !important;\n            }\n        "], ["\n            animation-delay: 0s !important;\n            animation-duration: 0s !important;\n            transition-delay: 0s !important;\n            transition-duration: 0s !important;\n\n            ::after,\n            ::before {\n                animation-delay: 0s !important;\n                animation-duration: 0s !important;\n                transition-delay: 0s !important;\n                transition-duration: 0s !important;\n            }\n        "]))); }, function (p) { return p.theme.text.SourceCodePro.family; }, function (p) { return p.theme.color.gray3; });
var templateObject_1, templateObject_2;
