export * from './catelog';
export * from './errors';
export * from './icons';
export * from './spotlight-registry';
export const HISTORY_KEY = '__fooxly_spotlight_history__';
export const HISTORY_LENGTH_KEY = '__fooxly_spotlight_history_length__';
export const SPOTLIGHT_THEME_KEY = '__fooxly_spotlight_theme__';
export const REGISTRY_UPDATE_EVENT_KEY = '__fooxly_spotlight_registry_update__';
export const THEME_UPDATE_EVENT_KEY = '__fooxly_spotlight_theme_update__';
export const TOAST_EVENT_KEY = '__fooxly_spotlight_toast_message__';
export const QUESTION_EVENT_KEY = '__fooxly_spotlight_question__';
export const QUESTION_RESULT_EVENT_KEY = '__fooxly_spotlight_question_result__';
export const SEARCH_INPUT_RESULT_EVENT_KEY = '__fooxly_spotlight_search_result__';
export const SEARCH_CLOSED_EVENT_KEY = '__fooxly_spotlight_search_closed__';
